# parameters.py

# VAR AUTO ENCODER PARAMETERS
IM_WIDTH = 160
IM_HEIGHT = 80
LATENT_DIM = 95

# ACTOR-CRITIC NETWORK PARAMETERS
OBSERVATION_DIM = 100
ACTION_DIM = 2

# HYPERPARAMETER
ACTION_STD_INIT = 0.2
LEARNING_RATE = 1e-4
BATCH_SIZE = 1
POLICY_CLIP = 0.2
GAMMA = 0.99
LAMBDA = 0.95
NO_OF_ITERATIONS = 7
SEED = 0


# TRAINING PARAMETERS
TRAIN_TIMESTEPS = 5e6
EPISODE_LENGTH = 75000
TEST_EPISODES = 30
NO_OF_TEST_EPISODES = 10


# SIMULATION PARAMETERS 
TOWN = 'Town02'
CAR_NAME = 'model3'
NUMBER_OF_VEHICLES = 30
NUMBER_OF_PEDESTRIAN = 10
CONTINUOUS_ACTION = True
VISUAL_DISPLAY = False

# PATHS
VAR_AUTO_MODEL_PATH = 'VAE'
RESULTS_PATH = 'Results_04'
PPO_MODEL_PATH = f'{RESULTS_PATH}/ppo_model'
VAE_MODEL_PATH = f'{RESULTS_PATH}/vae_model'
CHECKPOINT_PATH = f'{RESULTS_PATH}/checkpoints'
LOG_PATH_TRAIN = f'{RESULTS_PATH}/runs/train'
LOG_PATH_TEST = f'{RESULTS_PATH}/runs/test'
TEST_IMAGES = f'{RESULTS_PATH}/test_images'

TF_LITE_PATH = f'{RESULTS_PATH}/tf_lite_models'


CHECKPOINT_LOAD = True
